# Generated by Django 3.0.7 on 2020-06-12 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weathershow', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='weathermodel',
            name='date',
        ),
        migrations.AddField(
            model_name='weathermodel',
            name='day',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='weathermodel',
            name='month',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='weathermodel',
            name='year',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='weathermodel',
            name='maxdegree',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='weathermodel',
            name='mindegree',
            field=models.TextField(blank=True, null=True),
        ),
    ]
