# Generated by Django 3.0.7 on 2020-06-13 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weathershow', '0003_auto_20200613_0129'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weathermodel',
            name='date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
