# Generated by Django 3.0.7 on 2020-06-14 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weathershow', '0004_auto_20200613_2203'),
    ]

    operations = [
        migrations.AddField(
            model_name='weathermodel',
            name='currentdegree',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='weathermodel',
            name='feeldegree',
            field=models.TextField(blank=True, null=True),
        ),
    ]
